#!/usr/bin/env sh
set -e

url="https://raw.githubusercontent.com/webuni/shell-task-runner/master/runner"
[ -f ./.runner ] && [ .runner -nt "$0" ] || wget -q "$url" -O- > .runner || curl -fso .runner "$url"
. ./.runner

_decorator()( _decorator_docker_compose_run "$@" )

# Update dependencies to the latest versions
task_deps__latest()( _run composer update 2>&1 )

# Update dependencies to the lowest versions
task_deps__lowest()( _run composer update --prefer-lowest 2>&1 )

# Run composer
# @service php
task_composer()( composer "$@" )

# Run tests
# @service php
task_tests()( "$(__fn phpunit-8 && echo "phpunit-8" || echo "phpunit")" --colors=always "$@" )

# Fix code style
# @service php
task_cs()( php-cs-fixer fix --ansi --allow-risky=yes "$@" )

# Analyse code
# @service php
task_analyse()( phpstan analyse -l 7 -c phpstan.neon --no-progress --ansi src "$@" )

# Remove all containers in project (use -v to remove volumes also)
task_clean()( _docker_compose down --remove-orphans  "$@" )

# Run shell with tools
# @service php
task_tools()( sh "$@" )
